### ISSUE TITLE
[disruption] Use `version.{branch}.json` or `X-Build-Id` to check for stale builds beforehand

### ISSUE THREAD

**Issue by arHSM** [slice/havoc#1]
Currently in disruption, the fetched build is fully parsed and scraped and then its build number is compared with the previous build number stored in the DB
 https://github.com/slice/havoc/blob/2a8d4c6a709e03bd0fca85ba54e7bd00a0579265/crates/disruption/src/main.rs#L53

We can improve upon this by either checking the `X-Build-Id` header after each request and drop parsing stale builds, or we can just diff for changes in

- https://discord.com/assets/version.stable.json
- https://ptb.discord.com/assets/version.ptb.json
- https://canary.discord.com/assets/version.canary.json

appropriately and then scrape the build accordingly...

> Note:
> clicking on these links may throw a `Access Denied: 1020` here, but they work when the headers that the browser automatically adds are not provided

**Comment by slice** [comment]
Great suggestion, thanks! Looks like this may lead to less necessary work, which is always a plus.

To support this, we could:
1. Move `FeBuild.hash` to `FeManifest`, since the hash is now considered to be "surface-level" information that is trivially accessible, just like the asset tags in the HTML
2. Add a `build_hash` column to the `detected_builds_on_branches`.

Although #2 makes me want to add a separate `builds` table and have the `detected_builds_on_branches` table reference it via foreign key instead, because I feel like we should only be storing one unique identifier for the build in that table, not both. It would lead to less duplication of information, too. (I'm assuming there's a single, one-to-one correspondence between build number and hash.)

In that case, should we use the hash or the number as the primary identifier, though? Does it matter? 🤔

**Comment by arHSM** [comment]
I believe we should use the hash as the primary identifier, since that doesn't require us to parse the build files as opposed to the build number

**Comment by slice** [comment]
Oh wait, yeah, that makes sense.
